### ISSUE TITLE
Not sure how to build/run project

### ISSUE THREAD

**Issue by cgregurich** [gboisse/gfx#101]
![gfxnotworking](https://github.com/gboisse/gfx/assets/14157190/ddbf6a1c-93a7-4b08-933f-c7afa72613f6)

I'm not sure if there is a how-to guide on how to build and run this project, or one of the simple example projects, but I haven't been able to figure it out yet. Here is what I'm seeing after trying the following from the root directory:

1. mkdir build
2. cd build
3. cmake ..
4. cmake --build .

Any help?

**Comment by gboisse** [comment]
mmh, seems like you're missing the latest Direct3D12 features in your system's `d3d12.h` header (i.e., DXR-1.1, mesh shaders, etc.).
You could try to install the latest Windows SDK (or update your OS altogether), I think that'd fix it.

Alternatively, I believe you should be able to use a newer version of `d3d12.h` without having to update the system, although this isn't something I've ever tried myself. Here's a more recent [d3d12.h](https://github.com/gboisse/gfx/files/14164805/d3d12.zip) file in case you'd want to give it a try.

**Comment by gboisse** [comment]
https://github.com/gboisse/gfx/pull/115 should fix this issue.
