### ISSUE TITLE
C6011 error with CMake release builds

### ISSUE THREAD

**Issue by pawkubik** [gboisse/gfx#152]
The current `master` fails on Release mode with MSVC (VS 2022 toolchain):

```
[build] gfx.cpp(8413): error C2220: the following warning is treated as an error
[build] gfx.cpp(7716) : warning C6011: Dereferencing NULL pointer 'parameter.parameter_'. : Lines: 7704, 7705, 7706, 7708, 7711, 7712, 7713, 7714, 7715, 7716
```

There is `GFX_ASSERT(parameter.parameter_ != nullptr)` above those lines, but the macro is disabled on release.

I already tried to fix this in #145 , but we probably need a different approach to avoid running some expensive checks on release.

This occurs only when compiling with CMake, e.g.:
- Directly from terminal with `cmake --build ...`
- From VSCode (does the same command under the hood)
- From VS2022 in CMake mode (you need to open the root directory directly to treat it as CMake project)

This **doesn't** occur when run from VS 2022 .sln file generated with CMake like this:
```
cmake CMakeLists.txt -B ./build -G "Visual Studio 17 2022" 
```

**Comment by pawkubik** [comment]
This can be all due to subtle differences in compiler settings. This warning follows some roughly specified heuristics which mostly makes sene.
https://learn.microsoft.com/en-us/cpp/code-quality/c6011?view=msvc-170#heuristics

> Another characteristic that the analysis engine uses as evidence of nullability is if the program explicitly checks for NULL.

**Comment by pawkubik** [comment]
Similar to #114

**Comment by gboisse** [comment]
Should be fixed with https://github.com/gboisse/gfx/pull/153, could you give it a try?

**Comment by pawkubik** [comment]
Tested the newest version with clean git clone and everything built without any changes.
