### ISSUE TITLE
CMakeLists Error - Beginner

### ISSUE THREAD

**Issue by petrasvestartas** [gboisse/gfx#18]
Hi,

Can I ask if there is any basic tutorial how to build the project using CMakeLists?

By default I get the following errors on Windows Visual Studio 2019 x64:

![image](https://user-images.githubusercontent.com/18013985/162626039-929b0cb1-588d-44ec-8562-4dc549bc421a.png)

**Comment by gboisse** [comment]
Hi,
It looks like you are missing the submodules, which contain those dependencies.
You can run the following command to fetch them: `git submodule update --init --recursive`.

**Comment by petrasvestartas** [comment]
```
git clone https://github.com/gboisse/gfx.git 
cd gfx
git submodule update --init --recursive
```
thanks it worked well, there are some minor warnings:
![image](https://user-images.githubusercontent.com/18013985/162638644-bda42955-3a58-4254-89e5-2b41114738b2.png)

Nevertheless example works fine:
![image](https://user-images.githubusercontent.com/18013985/162638660-5c226178-e3a4-483a-9841-bc596de1d5fa.png)

**Comment by petrasvestartas** [comment]
Is there a documentation how to rotate camera by mouse ?
Or using other geometry types like lines and points?

**Comment by gboisse** [comment]
Glad to hear that you got it working.

In the sample, camera movement isn't implemented yet:
https://github.com/gboisse/gfx/blob/e28360b18acd345cef07fb4db491a5ed3ee5711d/examples/common/fly_camera.cpp#L66-L94

But you can find some open source camera libraries which should work fine, such as for instance:
- Arcball camera: https://github.com/nlguillemot/arcball_camera
- Fly-through camera: https://github.com/nlguillemot/flythrough_camera

I'd recommend opening separate issues for questions that aren't related to the original topic however.
It would make things easier to find for others 🙂

**Comment by petrasvestartas** [comment]
Thank you for an answer.
It would be nice if you could implement these libraries to your project. 

Nevertheless, thank you for an answer;)
