### ISSUE TITLE
Going headless

### ISSUE THREAD

**Issue by sayan1an** [gboisse/gfx#36]
How? Context creation offers two overloads - one asks for a window handle and the other asks for a D3D device handle. For headless mode, I guess we have to use the second overload using D3D device handle. However, I'm stuck at creating a D3D device. 

I need some something simple: like: `getMeADevice(int index)`, where `index` represents one of the several GPU adapters in the system. Please let me know!

As a side note: I can already decouple rendering resolution from display-frame-buffer resolution using custom render-targets or compute-shaders.

**Comment by gboisse** [comment]
Headless, do you mean window-less?
It should be fairly straightforward to add a window creation flag for this, something like `kGfxCreateWindowFlag_HideWindow`:
https://github.com/gboisse/gfx/blob/b83878e562c2c205000b19c99cf24b13973dedb2/gfx_window.h#L41-L45

But from your message, it seems this is more about choosing an adapter.
Currently, `gfx` implements this scoring scheme to pick the best adapter available in the system:
https://github.com/gboisse/gfx/blob/b83878e562c2c205000b19c99cf24b13973dedb2/gfx.h#L1127-L1166

I could add an overloaded `gfxCreateContext()` that takes an `IDXGIAdapter1*` as an input parameter, would that fix your problem?

**Comment by sayan1an** [comment]
To be more specific, I would like to run gfx on a remote server with only cmd-line access. So, by headless I meant a desktop without a display - e.g. a remote server or an AWS cloud instance. Is window-less same as head-less in this regard? 

In this setting, an overloaded `gfxCreateContext()` that takes an `IDXGIAdapter1*` is the solution?

**Comment by gboisse** [comment]
To me headless means opening up a "hidden window" but I'm certainly no expert here.

The `gfxCreateContext()` accepting an `IDXGIAdapter1*` would be a solution to pick a specific GPU (as opposed to the built-in classification that's currently in place in `gfx`) but I don't think it should have much impact w.r.t. headless or running on a server.

**Comment by sayan1an** [comment]
I see your point. However, I wonder if one can create a window, albeit hidden, on a headless system! Would GLFW fail when a system has no-display?  

I still think specifying an adapter to use for context creation is useful, but for reasons other than above.

**Comment by gboisse** [comment]
Added the option to pass in a selected `IDXGIAdapter*` to `gfxCreateContext()` as well as a new `kGfxCreateWindowFlag_HideWindow` window creation flag: https://github.com/gboisse/gfx/commit/9adc37170960b7eec85f084e12c48e701ca3f727.
