### ISSUE TITLE
New glTF importer crashes when objects have no valid name

### ISSUE THREAD

**Issue by gboisse** [gboisse/gfx#49]
So, it seems that `cgltf` returns `nullptr` names on objects that have no valid name, which crashes `std::string` as they do not accept `nullptr` assignments (which is a really annoying thing if you ask me): https://github.com/gboisse/gfx/commit/c31f5ceebf2b54a83c3c982cde0c6b6c5865fc81 (could cause the crash by trying to load the Sponza scene)

This ticket is mostly to track whether you think there's other places where this check should be added?

**Comment by maoliver-amd** [comment]
Side effect of having multiple sponza scenes, I clearly tested the wrong one.
